apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-api-mysql-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.1.83
    path: /data/k8s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-api-mysql-pvc
  namespace: dev-api
spec:
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
