---
apiVersion: v1
kind: Service
metadata:
  name: dev-api-java
  namespace: dev-api
spec:
  type: NodePort
  selector:
    app: dev-api-java
  ports:
  - name: dev-api-java-port
    protocol: TCP
    port: 8080
    targetPort: web
