apiVersion: v1
kind: PersistentVolume
metadata:
  name: wayne-mysql-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.1.161
    path: /data/app/k8s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wayne-mysql-pvc
  namespace: kube-system
spec:
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
