apiVersion: v1
kind: Service
metadata:
  name: dev-api-redis
  namespace: dev-api
  labels:
    name: dev-api-redis
spec:
  type: NodePort
  ports:
  - name: dev-api-redis
    port: 6379
    targetPort: redis
  selector:
    name: dev-api-redis
